mutation CreateCourse($coachId: UUID!, $title: String!, $description: String!) @auth(level: USER) {
  course_insert(data: {coachId: $coachId, title: $title, description: $description, createdAt_expr: "request.time", updatedAt_expr: "request.time"})
}

query ListCourses @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public") {
  courses {
    id
    title
    description
    coach {
      id
      displayName
    }
  }
}

mutation UpdateSubmission($id: UUID!, $grade: Float, $feedback: String) @auth(level: USER) {
  submission_update(key: {id: $id}, data: {grade: $grade, feedback: $feedback, updatedAt_expr: "request.time"})
}

query GetUserCourses($userId: UUID!) @auth(level: USER) {
  user(id: $userId) {
    courses_via_Enrollment {
      id
      title
      description
    }
  }
}