type User @table {
  displayName: String!
  email: String!
  userType: String!
  photoUrl: String
  bio: String
}

type Course @table {
  coach: User!
  title: String!
  description: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  difficultyLevel: String
  tags: [String]
}

type Material @table {
  course: Course!
  title: String!
  contentType: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  content: String
  orderInCourse: Int
}

type Assignment @table {
  course: Course!
  creator: User!
  title: String!
  dueDate: Date!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  description: String
  maxPoints: Int
}

type Submission @table {
  assignment: Assignment!
  student: User!
  submissionDate: Timestamp!
  status: String!
  createdAt: Timestamp!
  updatedAt: Timestamp!
  submissionContent: String
  grade: Float
  feedback: String
}

type Enrollment @table(key: ["student", "course"]) {
  student: User!
  course: Course!
  enrollmentDate: Timestamp!
  status: String!
  completionDate: Timestamp
}